feat: variables
cairo-book/cairo-book.github.io pull request #18
Opened 2023-04-03 18:41 UTC by enitrat

2023-04-03 19:35 UTC, fricoben requested changes
Looks good, have some questions and some small changes to make.

2023-04-03 19:35 UTC, fricoben commented on src/ch02-01-variables-and-mutability.md
> +your _cairo_projects_ directory by using `scarb new variables`.
Did you previously explained what is `scarb` anon ? Cause idk what it is

2023-04-03 19:35 UTC, fricoben commented on src/ch02-01-variables-and-mutability.md
> +```swift
swift ?

2023-04-03 19:35 UTC, fricoben commented on src/ch02-01-variables-and-mutability.md
> +if you change its type. For example, say our program performs a type conversion between the
Good note 🫡

2023-04-03 19:35 UTC, fricoben commented on src/ch02-01-variables-and-mutability.md
> +The first `x` variable has a u64 type while the second 'x' variable has a felt252 type.
the second `x` instead of the second 'x'

`felt252` instead of felt252

2023-04-03 19:36 UTC, enitrat commented on src/ch02-01-variables-and-mutability.md
> +However, the language abstracts this model and gives you the option to make your variables mutable. Let’s explore how and why Cairo enforces immutability, and how you can make your variables mutable.
no the `mut` concept is new

2023-04-03 19:36 UTC, enitrat commented on src/ch02-01-variables-and-mutability.md
> +your _cairo_projects_ directory by using `scarb new variables`.
yes, in the chapter 1.2

2023-04-03 19:37 UTC, enitrat commented on src/ch02-01-variables-and-mutability.md
> +```swift
rust has weird syntax highlighting when used with single quotes

2023-04-04 02:20 UTC, hurrikaanig commented
Looks good to me !

2023-04-04 02:20 UTC, hurrikaanig approved these changes

2023-04-04 09:14 UTC, enitrat commented
@fricoben I think i'm going to keep the part about immutable variables like it is currently. I think a lengthy explanation is required for readers not familiar to Rust

2023-04-04 14:15 UTC, merged