Data type page
cairo-book/cairo-book.github.io pull request #21
Opened 2023-04-04 08:40 UTC by Cheelax

2023-04-04 13:55 UTC, enitrat requested changes
Thank you for the PR!

I made some comments about the changes to bring.

2023-04-04 13:55 UTC, enitrat commented on src/SUMMARY.md
> +  - [Common Programming Concepts](ch02-00-common-programming-concepts.md)
you will need to rebase this with main, this should be in section 2. (cf file in https://github.com/cairo-book/cairo-book.github.io/pull/18)

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +data is being specified so it knows how to work with that data. his section covers two subsets of data types: scalars and compounds.
> his

This

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +let guess = cast("42",u32);
What? this is not valid cairo code

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +In Cairo when you don't specify the type of a variable/argument, its type is a field element (represented by the keyword `felt`). In the context of Cairo, when we say “a field element” we mean an int
In Cairo, if you don't specify the type of a variable or argument, its type defaults to a field element, represented by the keyword `felt252`.

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> + is a very large (prime) number (currently it is a 252-bit number, which is a number with 76 decimal digits). When we add, subtract or multiply and the result is outside the range above, there is an
where P is a very large prime number

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +, an overflow will occur which can bring the result down to 7. It’s a well-known mathematical fact that unless the denominator is zero, there will always be a value x satisfying `denominator * x = nu
If this seems implausible, keep in mind that if 3 * x falls outside the range -P/2 < x < P/2, an overflow occurs, potentially bringing the result down to 7

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +### Scalar Types
Felts are scalar types and thus should be included

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +A *scalar* type represents a single value. Cairo has three primary scalar types:
You need to mention the fact that these types are custom types defined in the core library and they're built from felts and add security features

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +|arch(32bit)| `usize`  |
`usize` are hardcoded to 32-bit (for now)

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +main() {
fn main(){

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +```Swift
use ```rust here (no capitalization)

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +Additionally, the `usize` type depends on the architecture of the
Not true yet, I would just remove this

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +| Numeric literals | Example       |
There are also octal and binary literals
https://github.com/starkware-libs/cairo/commit/51ebb3ffd243d6eaee8111a44ee2b0bcda3d7ee9

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +> When you’re compiling in debug mode, Cairo includes checks for integer overflow
Compiling in debug mode is not a thing, this is only valid from Rust. The compiler doesn't check for overflows at compile time.
Remove the part about panics

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +```rust
You're demonstrating operations with felts. Use u128 instead, we want readers to use integer types as much as possible

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +### Felts Type
You need to add a sentence explaining that while felts are the data type used by default in Cairo programs, programmers should abstain from using the `felt252` type when possible for security measures.

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +Flow”][control-flow]<!-- ignore --> section.
You can add the reference (at the bottom of the md page) even if the ref doesn't exist yet.

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +Cairo’s `short sting` type is the language’s most primitive alphabetic type, the length is at most 31 characters as they are stored in a felt. Here are
Cairo doesn't have a native type for strings, but you can store characters forming what we call a "short string" inside `felt252`s

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +```Rust
```rust
use debug::PrintTrait;
fn main() {
    let tup = (500, 6, true);

    let (x, y, z) = tup;

    if y == 6 {
        'y is six!'.print();
    }
}
```

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +Arrays are useful when you want your data allocated on the stack rather than
Remove this part, there are no such things as stack and heap in Cairo

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +You write an array’s type by passing the type like this:
You can pass the expected type of items inside the array when instantiating the array like this

```rust
let mut arr = ArrayTrait::<u128>::new();
```

(consistency with the above example)

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +like this:
If we're presenting arrays, we need to present `get()`, `at()`, and explain their differences.

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +By using the ArrayTrait::get() function because it returns an Option type, meaning that if you're trying to access an index out of bounds, it will return None instead of exiting your program, meaning
formatting: `ArrayTrait::get()`

2023-04-04 13:55 UTC, enitrat commented on src/ch02-02-data-types.md
> +```Rust
incorrect snippet

```rust
use array::ArrayTrait;
use box::BoxTrait;

fn main() -> u128 {
    let mut arr = ArrayTrait::<u128>::new();
    arr.append(100_u128);
    let length = arr.len();
    match arr.get(length - 1_usize) {
        Option::Some(x) => {
            *x.unbox()
        },
        Option::None(_) => {
            let mut data = ArrayTrait::new();
            data.append('out of bounds');
            panic(data)
        }
    } // returns 100
}
```

2023-04-04 14:56 UTC, Cheelax commented on src/ch02-02-data-types.md
> +A *scalar* type represents a single value. Cairo has three primary scalar types:
Can you confirm if you are talking about others scalar types or Compound Types too?

2023-04-04 15:14 UTC, Cheelax commented on src/ch02-02-data-types.md
> +### Felts Type
added this at the end of felt description:  The felt252 type is a fundamental type that serves as the basis for creating custom types in the core library. All other types, except felt252, are built on top of this foundational type by combining felts with additional security features.

It is highly recommended for programmers to use the custom types instead of the felt252 type whenever possible, as the custom types come with added security features that provide extra protection against potential vulnerabilities in the code. By utilizing these custom types, programmers can ensure that their programs are more secure and less susceptible to attacks or other security threats.

2023-04-04 18:58 UTC, enitrat commented on src/ch02-02-data-types.md
> +### Felts Type
> by combining felts

Not 100% accurate, u128 is built on top of felt252 but it's not a combination of felts

2023-04-04 19:00 UTC, enitrat commented on src/ch02-02-data-types.md
> +### Felts Type
> utilizing

using

> custom types

suggestion: standard/core types? I think it's best to be more precise, we're using the types from the corelib

2023-04-04 20:29 UTC, enitrat requested changes

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
>  A *scalar* type represents a single value. Cairo has three primary scalar types:
four: felts!

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
>  integers, booleans, and characters. You may recognize
characters don't exist so back to three, lol

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
> +The `get` function returns an `Option<Box<@T>>`, which means it returns a pointer to a box containing a reference to the element at the specified index if that element exists in the array. If the ele
> reference

it's not a reference, it's a _snapshot_

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
> +The `at` function, on the other hand, directly returns a reference to the element at the specified index using the `unbox()` operator to extract the value stored in a box. If the index is out of boun
snapshot here as well

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
> +The `get` function returns an `Option<Box<@T>>`, which means it returns a pointer to a box containing a reference to the element at the specified index if that element exists in the array. If the ele
This method is useful when you expect to access indices that may not be within the array's bounds and want to handle such cases gracefully without panics.

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
> +The `at` function, on the other hand, directly returns a reference to the element at the specified index using the `unbox()` operator to extract the value stored in a box. If the index is out of boun
> so it's more prone to segmentation faults.

segmentation faults don't exist in Cairo.

> This function is more concise than `get`, but it doesn't provide any index checking, so it's more prone to segmentation faults.

Replace by

You should only use `at` when you want the program to panic if the provided index is out of the array's bounds, which can prevent unexpected behavior.

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
> +In summary, `get` is safer because it returns an `Option` that allows checking if the index is valid, while at is more concise but can cause segmentation faults if the index is out of bounds.
Well, the whole point of using `get` is to provide error management, we should mention that.

replace by:

In summary, use `at` when you want to panic on out-of-bounds access attempts, and use `get` when you prefer to handle such cases gracefully without panicking.

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
> +You can access elements of an array using indexing.
This is not true, you can't access elements with indexing... (if you meant like arr[2])

2023-04-04 20:29 UTC, enitrat commented on src/ch02-02-data-types.md
> +By using the `ArrayTrait::get()` function because it returns an Option type, meaning that if you're trying to access an index out of bounds, it will return None instead of exiting your program, meani
Redundant, you can remove the section, but keep the example below to show how to manage errors manually

2023-04-04 20:31 UTC, enitrat commented on src/ch02-02-data-types.md
> +In this example, the variable named `first` will get the value `0` because that
but if we use `get` we don't get the value, do we?

let's use `at` in this example, as `get` is used below.

```
let first = *a.at(0_usize);
let second = *a.at(1_usize);
```

2023-04-05 07:16 UTC, enitrat approved these changes
great, thank you!

2023-04-05 07:16 UTC, merged