Feat: cairo verify tool
cairo-book/cairo-book.github.io pull request #249
Opened 2023-06-22 15:39 UTC by julio4

Following our discussion in #209, here's a first version of a simple CLI tools (named `cairo-verify`).

### Change to `mdbook-cairo`

The `mdbook-cairo` is no longer a backend. It's now a mdbook preprocessor that only removes the `// TAG` lines in code blocks.

**!! Install it again !!**
```sh
cargo install --path mdbook-cairo
```

### `cairo-verify`

The `cairo-verify` tool is designed to wrap all cairo and starknet plugins for quickly verifying cairo programs.

#### Setup

```sh
cargo run --bin cairo-verify
```

Or full install:
```sh
cargo install --path cairo-verify
```

### Usage

The tool scans for all `*.cairo` files in the specified directory and performs the following actions:

For a Starknet contract:
- `starknet-compile`
- If it has tests: `cairo-test --starknet`

Cairo program:
- If it has a `main` function: `cairo-run`
- Else, `cairo-compile`
- If it has tests: `cairo-test`
- `cairo-fmt`

To specify which tests to run, you can add a comment at the top of your file with the following format:

```rust
// TAG: <tag1>
// TAGS: <tag1>, <tag2>
```

Here is a list of available tags:
- `does_not_compile`: don't run `cairo-compile`/`starknet-compile`
- `does_not_run`: don't run `cairo-run`
- `ignore_fmt`: don't run `cairo-fmt`
- `tests_fails`: don't run `cairo-test`/`cairo-test --starknet`

You can skip and ignore a specific test by adding the corresponding flag:

```sh
$ cairo-verify --help

Usage: cairo-verify [OPTIONS]

Options:
  -p, --path <PATH>    The path to explore for *.cairo files [default: ./listings]
  -v, --verbose        Print more information
  -q, --quiet          Only print final results
  -f, --formats-skip   Skip cairo-format checks
  -s, --starknet-skip  Skip starknet-compile checks
  -c, --compile-skip   Skip cairo-compile checks
  -r, --run-skip       Skip cairo-run checks
  -t, --test-skip      Skip cairo-test checks
      --file <FILE>    Specify file to check
  -h, --help           Print help
  -V, --version        Print version
```

In CI, it's preferable to reduce output, so run `cairo-verify` with the `--quiet` flag.

TODO:
- [ ] Fix CI: we have to run `cairo-verify -q`, but it rely both on rust and cairo so we need to change the docker image as well

2023-06-24 15:02 UTC, julio4 commented
@enitrat @glihm, could you please provide some feedback on this?

2023-06-24 19:17 UTC, enitrat commented on cairo-verify/src/main.rs
> +        println!("\n{}\n", "ALL TESTS PASSING!".green().bold());
ALL TESTS PASSED intead?

2023-06-24 19:17 UTC, enitrat commented on cairo-verify/src/main.rs
> +    let file = File::open(file_path).expect("Failed to open file");
we should add the file_path in the error message

2023-06-24 19:17 UTC, enitrat commented on cairo-verify/src/main.rs
> +    // for line in reader.lines() {
unused line

2023-06-24 19:17 UTC, enitrat commented on cairo-verify/src/utils.rs
> +pub fn clickable(input: &str) -> String {
super cool

2023-06-24 19:17 UTC, enitrat commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoRun => vec!["--program"],
`cairo-run` doesn't have a `--program` flag

2023-06-24 19:18 UTC, enitrat commented
Amazing PR @julio4 🙃

2023-06-25 00:11 UTC, glihm requested changes
In general, that's an awesome PR @julio4!

Some feedbacks are in the review items, but here are more general ones:

1. The UX is awesome, the tool feels great in a terminal, very quick and nice to use.

2. You will see in my comments too, but to easily switch between cairo versions, it could be great to be able to pass the binaries folder to the tool. This ensures that users working actively on cairo with several versions installed can easily switch the version with a simple command line argument.

3. Consider applying `cargo fmt` and `cargo clippy --all -- -D warnings` inside `cairo-verify`. :+1:

Thanks again for this massive rework, loving the tool! :heart:

2023-06-25 00:11 UTC, glihm commented on cairo-verify/src/main.rs
> +        if !tags.contains(&Tags::DoesNotRun) && !cfg.run_skip {
You should also check for `DoesNotCompile`, because if I have a file with a `main` function `should_be_runnable` is `true`, and if I have a TAG `does_not_compile`, this generates a run error, which is expected as it does not compile, but reported as an error.

Or do we want the user to always write `does_not_run, does_not_compile`?

I have tested this for example on the file `no_listing_21_function_return_values_2.cairo`.

```rust
// TAG: does_not_compile                                                                                                                                                         

use debug::PrintTrait;

fn main() {
    let x = plus_one(5);

    x.print();
}

fn plus_one(x: u32) -> u32 {
    x + 1
}
```

And then running `cairo-verify -p listings/ch02-common-programming-concepts/`.

```bash
Run Errors: 37
 - no_listing_32_array_at.cairo
 - no_listing_26_if_let.cairo
 - no_listing_11_type_casting.cairo
 - no_listing_12_tuple_type.cairo
 - no_listing_35_array_span.cairo
 - no_listing_08_numeric_operations.cairo
 - no_listing_14_tuple_types.cairo
 - no_listing_21_function_return_values_2.cairo <<<<<<< present here
 - ...
```

2023-06-25 00:11 UTC, glihm commented on cairo-verify/src/tags.rs
> +            "does_not_compile" => Some(Tags::DoesNotCompile),
As mentioned above, `does_not_compile` implies `does_not_run`.

2023-06-25 00:11 UTC, glihm commented on mdbook-cairo/src/lib.rs
> +                    in_code_block = in_code_block ^ line.starts_with("```");
nice bitwise approach, love it.

`in_code_block ^= line.starts_with("```");` would have been more idiomatic. :+1:

2023-06-25 00:11 UTC, glihm commented on mdbook-cairo/src/lib.rs
> +                        if RE.is_match(line) {
Consider using more explicit names for static variables.

2023-06-28 08:06 UTC, julio4 commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoRun => vec!["--program"],
When using `cairo-run <program>` I have `cairo-run: error: unrecognized arguments` (cairo-run 0.11.2).
What is the correct way of using it?

2023-06-28 08:09 UTC, julio4 commented on cairo-verify/src/main.rs
> +        if !tags.contains(&Tags::DoesNotRun) && !cfg.run_skip {
Good catch! It's better that way.

2023-06-28 08:15 UTC, julio4 commented on cairo-verify/src/tags.rs
> +            "does_not_compile" => Some(Tags::DoesNotCompile),
I believe that the `Tags` enum should not provide any information about tag implications. Instead, this logic should be handled in the `main` file. 
Let me know if you think it would be better to handle the tag implication logic here.

2023-06-28 08:19 UTC, julio4 commented on cairo-verify/src/cmd.rs
> +pub enum Cmd {
`cairo-root` is a great idea. I suggest that we first merge this initial version so we can already fix the current issues, and I'll add this soon.

2023-06-28 08:52 UTC, enitrat commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoRun => vec!["--program"],
The `cairo-run` on your computer is the one from cairo0! 
You need to delete it from your path and replace it with the cairo1 one.

2023-06-28 09:06 UTC, julio4 commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoRun => vec!["--program"],
Well, I shouldn't be the one making installation instructions 😢 
Fixed now, sorry for that.

2023-06-28 18:12 UTC, enitrat commented on cairo-verify/src/tags.rs
> +            "does_not_compile" => Some(Tags::DoesNotCompile),
> Instead, this logic should be handled in the main file.

agreed

2023-06-28 18:31 UTC, glihm commented on cairo-verify/src/tags.rs
> +            "does_not_compile" => Some(Tags::DoesNotCompile),
Yes I do agree it was to mention it here too. Definitely in the main. 👍🏻

2023-06-28 18:40 UTC, enitrat commented
@julio4 i'm modifying the cairo files to ensure that everything runs accordingly to how it should, and I make some modification to the rust files, don't forget to pull my changes when I push

2023-06-28 19:10 UTC, enitrat commented
feature request: if something is marked with `does_not_compile`, or `does_not_run`, then we should still run it and verify that indeed it does not compile / does not run

2023-06-29 13:05 UTC, julio4 commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoTest(_) => vec!["--starknet"],
I believe you should remove `--starknet` argument for non-contracts cairo files.

2023-06-29 13:07 UTC, enitrat commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoTest(_) => vec!["--starknet"],
It's necessary if we want to test starknet contracts, and it doesn't change anything for pure cairo tests, so let's 
add it by default instead of having another extra condition to take care of.

2023-06-29 13:16 UTC, julio4 commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoTest(_) => vec!["--starknet"],
In that case we should remove the `StarknetTest` variant in the `Cmd` enum.

2023-06-29 13:24 UTC, enitrat commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoTest(_) => vec!["--starknet"],
Ah, right, I didn't see it was there. I'll revert my changes

2023-06-29 13:31 UTC, julio4 commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoTest(_) => vec!["--starknet"],
If `--starknet` has no side effect for pure cairo, then it's a good idea to keep things simple and remove `StarknetTest`. We just have to replace it by `CairoTest`!

2023-06-29 13:33 UTC, julio4 commented on cairo-verify/src/cmd.rs
> +            Cmd::CairoTest(_) => vec!["--starknet"],
If there could be additional logic only for Starknet contract in the future, then just remove the flag.

2023-06-29 16:40 UTC, glihm commented
> @glihm should we `cargo install` or `cargo run --bin` in our GH action? what's the fastest?

I usually see `cargo install` with the `--locked` as @julio4 did. :+1: It's totally fine IMHO.

2023-06-29 16:54 UTC, glihm commented on cairo-verify/src/cmd.rs
> +            let full_path = r.join(PathBuf::from("target/release")).join(binary);
I would remove the `target/release` as this takes the hard assumption that the user compiles it and on how the user organizes his files. When it can be a server or GH action with binaries imported/installed directly without compilation.

2023-06-30 08:37 UTC, enitrat approved these changes

2023-06-30 08:38 UTC, merged