Added StorageAccess to appendix 3
cairo-book/cairo-book.github.io pull request #258
Opened 2023-06-23 05:13 UTC by ametel01

closes #232

2023-06-23 10:45 UTC, enitrat requested changes

2023-06-23 10:45 UTC, enitrat commented on src/appendix-02-operators-and-symbols.md
Formatting broke here

2023-06-24 20:36 UTC, enitrat commented on src/appendix-03-derivable-traits.md
> +#[storage]
The example seems odd here. I don't think it's valid even with the new syntax.

2023-06-24 21:06 UTC, ametel01 commented on src/appendix-03-derivable-traits.md
> +#[storage]
Could you elaborate more? Indeed the compiler does not complain about custom structs not deriving StorageAccess. For your reference this is the PR i referred to:
https://github.com/starkware-libs/cairo/pull/3062

2023-06-24 21:12 UTC, enitrat commented on src/appendix-03-derivable-traits.md
> +#[storage]
Sorry, what I meant here was targeted to the `#[storage]` struct being outside of a contract - ideally, we want every code snippet to be compilable. That means that you should wrap this struct inside a contract, as a standalone storage struct doesn't make a lot of sense.

2023-06-25 09:23 UTC, enitrat approved these changes
LGTM :100: Thanks @ametel01

2023-06-25 09:24 UTC, merged