Feat/enums
cairo-book/cairo-book.github.io pull request #32
Opened 2023-04-08 19:11 UTC by Th0rgal

Hey,

Here is my page about Enums (see #26 ).  I tried to give working examples that make sense. The last one is a bit too long in my opinion but hopefully we should be able to make it shorter when we will have working loops with automatic gas management (may be we already do and I missed it). 

What do you thinK? :)

2023-04-09 13:03 UTC, fricoben requested changes
Some questions and propositions

2023-04-09 13:03 UTC, fricoben commented on src/ch05-01-enums.md
> +    find_value_recursive(arr, value, index + 1_usize)
A bit difficult considering that we shouldn't see a lot of recursive loops anymore.

2023-04-09 13:03 UTC, fricoben commented on src/ch05-01-enums.md
> +}
Maybe show what's printed when your run ?

2023-04-09 13:06 UTC, Th0rgal commented on src/ch05-01-enums.md
> +            },
exactly, I think it should be explained better in the iris docs about match

2023-04-09 13:07 UTC, Th0rgal commented on src/ch05-01-enums.md
> +    find_value_recursive(arr, value, index + 1_usize)
Right, as explained in the note this is temporary, we can update the example when loops are available

2023-04-09 13:08 UTC, Th0rgal commented on src/ch05-01-enums.md
> +}
Alright, I will remove it from the source code comment and add it at the end, "run output" or something

2023-04-09 16:43 UTC, hurrikaanig commented on src/ch05-01-enums.md
> +In this example, the Animal enum has three variants: `Elephant`, `Ant` and `Giraffe`.
Forgot quotes on Animal

2023-04-09 17:28 UTC, fricoben commented
close #32

2023-04-09 17:29 UTC, enitrat commented on src/ch05-01-enums.md
> +            Animal::Elephant((weight, _)) => {
might be worth explaining what `_` stands for

2023-04-09 17:29 UTC, enitrat commented on src/ch05-01-enums.md
> +enum Animal {
I personally think this example doesn't demonstrate the power of enums very well and is quite confusing.
It would work better with something more constrained. I actually like the rustbook example with Messages more, because 
- It implies that you can only have 4 types of messages in your application and makes it more obvious
- Each message has a different function and must then be treated differently (which is not clear with animals)
- Each enum variant value is a different type, which explains well what you're trying to demonstrate here
- The `message.call` example (which I used in Starklings) is I think very explicit

I'll leave it up to you to decide if you want to change it :)

2023-04-10 09:33 UTC, Th0rgal commented on src/ch05-01-enums.md
> +enum Animal {
I agree, tbh I couldn't find one example that worked very well for both the `Custom Types` and the `Traits implementation` sections. Do you have an idea in mind of a trait that would make sense for the Messages enum?

2023-04-10 09:33 UTC, Th0rgal commented on src/ch05-01-enums.md
> +            Animal::Elephant((weight, _)) => {
will do

2023-04-10 11:50 UTC, enitrat commented on src/ch05-01-enums.md
> +enum Animal {
Why not a simple `message.process` that acts differently based on the variant received?

2023-04-10 12:00 UTC, Th0rgal commented on src/ch05-01-enums.md
> +enum Animal {
let's do it

2023-04-10 12:30 UTC, Th0rgal commented
should be good now @enitrat

2023-04-10 12:33 UTC, enitrat approved these changes
Great work :100:

2023-04-10 12:33 UTC, merged