feat: ownership
cairo-book/cairo-book.github.io pull request #40
Opened 2023-04-10 17:24 UTC by enitrat

Closes #34 

Time spent: 4 hours

2023-04-10 17:46 UTC, hurrikaanig commented on src/ch03-01-what-is-ownership.md
> +references or multiple writes to the same memory address, and ensures the soundness of Cairo programs
Maybe we should explain soundness or provide a link that explains it

2023-04-10 18:01 UTC, wraitii commented on src/ch03-01-what-is-ownership.md
> +By default, a value may not go out of scope unless it was previously moved. For example, the following code does not compile:
In particular, this reads a little weird to me. It would be more obvious to say that 'Upon going out of scope, the `_drop_` function is called on the type. Therefore, this function must exist for code to compile.

2023-04-10 18:02 UTC, fricoben requested changes
90% question and comments to be sure I understood (that's a good experiment tho to be sure a random dev understand). 

10% minor changes.

Gud PR 🔥

2023-04-10 18:03 UTC, wraitii commented on src/ch03-01-what-is-ownership.md
> +By default, a value may not go out of scope unless it was previously moved. For example, the following code does not compile:
This I believe differs from Rust where it's fine to not have this Drop thing ? I'm actually not sure how that's handled

2023-04-10 19:40 UTC, enitrat commented on src/ch03-00-understanding-ownership.md
> +statically ensure that in every Cairo program, a value is used exactly once.
No, here it's just for the linear type system. It has nothing to do with immutable memory.
It just makes sure that each instantiated variable is consumed (moved or dropped)

2023-04-10 19:41 UTC, enitrat commented on src/ch03-00-understanding-ownership.md
> +and forbidding copying and dropping values by default. In this chapter, we’ll
Why do you think this? This is actually at the core of this ownership/linear type system

2023-04-10 19:42 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +boilerplate code.
Not sure as it doesn't belong in the section above either.

2023-04-10 19:43 UTC, Th0rgal commented
Nice some reading before bed

2023-04-10 19:46 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +by checking at compile time that all the dictionaries are squashed.
Does it become clearer after reading the rest? I don't really want to be very descriptive in the introduction 🤔 
It's just an "abstract" concept behind the design of the language but it justifies this whole page.

2023-04-10 19:47 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +You can append values to an `Array` using the `append` method:
well `append` is self-explanatory 😆  its a synonym to `add`

2023-04-10 19:47 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +using the same instance of `arr` in `foo`.
yes exactly
would it make more sense if I had two different function names for the sake of the example?

2023-04-10 19:48 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +While Arrays and Dictionaries can't be copied, custom types that don't contain either of them can be.
types that don't contain an Array or a Dict, unlike this one for ex
```
struct MyType{
  arr:Array<u128>
}
```

2023-04-10 19:50 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +#[derive(Copy, Drop)]
You can still pass values by reference, this is covered in the next page. But yes almost every custom type will derive these two trait implementations

2023-04-10 19:50 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +```
because `A` doesn't derive the `Drop` implementation, so the compiler doesn't know how to drop it

2023-04-10 20:16 UTC, Th0rgal commented
Okay I'm hyped for the snapshots now

2023-04-10 21:04 UTC, wraitii commented on src/ch03-00-understanding-ownership.md
> +and forbidding copying and dropping values by default. In this chapter, we’ll
It's not obvious what that means, particularly 'dropping values', unless you've already read the chapter. Seems odd as an intro to me.

It might make more sense if you're coming from rust but I'm not sure that this should be assumed.

But then again I'm not sure that introducing this as a 'linear type system' helps either because I have no clue what the means and reading wikipedia doesn't help, so maybe this comment is irrelevant as a whole.

2023-04-10 21:07 UTC, wraitii commented on src/ch03-00-understanding-ownership.md
> +and forbidding copying and dropping values by default. In this chapter, we’ll
(And by 'this comment' I mean my comments on this section, though I am not certain that this introduction works really well if one needs to be deep into type theory to actually understand it.

2023-04-11 08:09 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +references or multiple writes to the same memory address, and ensures the soundness of Cairo programs
I feel like that would be too much for the introduction, + it's not directly related to the subject here 🤔

2023-04-11 08:15 UTC, enitrat commented on src/ch03-00-understanding-ownership.md
> +statically ensure that in every Cairo program, a value is used exactly once.
added: "This linear type system helps preventing runtime errors by ensuring that operations that could cause such errors, such as writing twice to a memory cell, are detected at compile time."

2023-04-11 08:21 UTC, enitrat commented on src/ch03-00-understanding-ownership.md
> +and forbidding copying and dropping values by default. In this chapter, we’ll
> though I am not certain that this introduction works really well if one needs to be deep into type theory to actually understand it.

Here's how I see it: Readers who are familiar with the concept will be able to grasp in a second what this chapter is about. Readers who are unfamiliar will read the rest to understand the terms introduced here.

Providing an explanation about what a linear type system is is not in the scope of the book

2023-04-11 08:21 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +boilerplate code.
ok

2023-04-11 09:03 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +from the body of the function that we might want to return as well.
This is actually the goal of this sentence - demonstrate how annoying and confusing it is to proceed this way to demonstrate how powerful borrowing with `ref` and `@` are.

2023-04-11 09:04 UTC, enitrat commented on src/ch03-01-what-is-ownership.md
> +By default, a value may not go out of scope unless it was previously moved. For example, the following code does not compile:
Drop is an entirely different concept in Rust as it just ensures that memory is freed.

2023-04-11 09:12 UTC, enitrat commented
@fricoben  - Comments addressed.
@wraitii - I reworked the `Drop` part, and introduced the part about `Destructors` that I forgot. I felt that it make more sense to introduce them in this order. It should be way more clear now, wdyt?

2023-04-11 09:22 UTC, wraitii commented on src/ch03-01-what-is-ownership.md
> +#### Copy Array data with Clone
This is a `####` instead of a  `###` which seems a little odd, as it implies it's under 'Destruct'

2023-04-11 09:26 UTC, wraitii commented
> @wraitii - I reworked the `Drop` part, and introduced the part about `Destructors` that I forgot. I felt that it make more sense to introduce them in this order. It should be way more clear now, wdyt?

Agreed, I think this is much more understandable now.
I'm just wondering what the `drop` function actually does? Can one manually implement it? Is it actually any different from `Destruct` then?

2023-04-11 09:28 UTC, enitrat commented
> I'm just wondering what the drop function actually does? Can one manually implement it? Is it actually any different from Destruct then?

As you said it's a "no-op" that just transfers ownership in the void. It compiles to the `drop` libfunc in Sierra but doesn't generate any CASM code.

2023-04-11 15:36 UTC, fricoben approved these changes
letzzz go

2023-04-11 15:36 UTC, merged