Traits WIP
cairo-book/cairo-book.github.io pull request #53
Opened 2023-04-14 14:05 UTC by shramee

Work in progress...

2023-04-14 16:02 UTC, shramee commented
Sure can! Thanks for taking a look 🤗

2023-04-15 10:39 UTC, enitrat requested changes
Thank you for the PR. I think we need to be more explicit and descriptive, as this book must remain understandable by people with only very basic programming knowledge.

I left comments that need to be addressed

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +Traits specify functionality blueprints that can be implemented. The specification includes a set of function signatures containing type annotations for parameters and return value.
Can you be more specific? It's not very clear to someone that is not familiar with traits. What can you do with them?

From the rust book
> A trait defines functionality a particular type has and can share with other types. We can use traits to define shared behavior in an abstract way.

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +
Can you add an explanation here? What do you define a `ShapeGeometry` trait for? 
It must be very explicit here, you must mention that all shapes share common methods such as areas, etc, and defining a geometry trait allows us to specify a shared behavior for all shapes

Once again quoting the Rust book for this

> A type’s behavior consists of the methods we can call on that type. Different types share the same behavior if we can call the same methods on all of those types. Trait definitions are a way to group method signatures together to define a set of behaviors necessary to accomplish some purpose.
...

+ Suggestion
> For example, let's say that we have multiple structs representing shapes. We want our application to be able to perform geometry operations on these shapes ...

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +
Can you add some explanation here?

> Here, we declare a trait using the trait keyword and then the trait’s name, which is ShapeGeometry in this case. Inside the curly brackets, we declare the method signatures that describe the behaviors of the type that implement this trait, which in this case is...

- traits can have multiple functions
-  instead of providing an implementation within curly brackets, we use a semicolon at the end of the declaration

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +
Be more explicit. You must detail what happens in your code snippet.

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +In the example above, `self` is a special keyword. When parameter with name `self` is used, the implemented functions are also attached to the instances of the type as methods. Here's an illustration
When a parameter with the name

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +In the example above, `self` is a special keyword. When parameter with name `self` is used, the implemented functions are also attached to the instances of the type as methods. Here's an illustration
Can you insert a link to ch04-03-method-syntax.html#defining-methods?

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +
Refering to my first comment:

> A trait defines functionality a particular type has and can share with other types. We can use traits to define shared behavior in an abstract way.

I think we should emphasize that non-generic traits are implemented for a single type, and that to define shared behavior common to multiple types we must use a generic trait syntax.

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +To use traits methods, you need to make sure the correct implementation(s) are imported. In the code above we imported `PrintTrait` from `debug` with `use debug::PrintTrait;` to use `print()` methods
Can you add a sentence that explains that when importing a trait, the compiler will look for implementation in the same modules as the trait, and that you don't need to explicitly import those?

2023-04-15 10:39 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +```rust
Great!

2023-04-16 10:51 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +Traits specify functionality blueprints that can be implemented. The specification includes a set of function signatures containing type annotations for parameters and return value.
@enitrat Cairo traits IMO are significantly different from Rust traits. To me, they don't seem to be coupled with  `types` in Cairo.

2023-04-16 10:53 UTC, enitrat commented on src/ch04-04-traits-in-cairo.md
> +Traits specify functionality blueprints that can be implemented. The specification includes a set of function signatures containing type annotations for parameters and return value.
Yes, however this becomes true with generic traits.

2023-04-16 14:57 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +To use traits methods, you need to make sure the correct implementation(s) are imported. In the code above we imported `PrintTrait` from `debug` with `use debug::PrintTrait;` to use `print()` methods
We already have this,
```
In some cases you might need to import not only the trait but also the implementation if they are declared in separate modules.
```

2023-04-16 15:02 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +
> `Here's what a simple trait declaration looks like.`

Swapped with,

> For example, let's say that we have multiple structs representing shapes. We want our application to be able to perform geometry operations on these shapes, So we define a trait `ShapeGeometry` that contains a blueprint to implement geometry operations on the shape like this,

2023-04-16 15:02 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +
Added this,

> Here our trait `ShapeGeometry` declares signatures for two methods `boundary` and `area`. When implemented, both these functions should return a `u64` and except parameters as specified by the trait.

2023-04-16 15:03 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +
Added,

> In the code above, `RectangleGeometry` implements the trait `ShapeGeometry` defining what the methods `boundary` and `area` should do. Note the the function parameters and return value types are identical to the trait specification.

2023-04-16 15:04 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +In the example above, `self` is a special keyword. When parameter with name `self` is used, the implemented functions are also attached to the instances of the type as methods. Here's an illustration
```diff
-In the example above, `self` is a special keyword. When parameter with name `self` is used, the implemented functions are also attached to the instances of the type as methods. Here's an illustration,
+In the example above, `self` is a special keyword. When a parameter with name `self` is used, the implemented functions are also [attached to the instances of the type as methods](ch04-03-method-syntax.md#defining-methods). Here's an illustration,
```

2023-04-16 15:06 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +
Replaced,

>You would want to write a trait when you want multiple types to implement some functionality in a standard way. To do this, we use generic types.

with

> Usually we want to write a trait when we want multiple types to implement a functionality in a standard way. However, in the example above the signatures are static and cannot be used for multiple types. To do this, we use generic types when defining traits.

2023-04-16 15:53 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +Traits specify functionality blueprints that can be implemented. The specification includes a set of function signatures containing type annotations for parameters and return value.
> Traits specify functionality blueprints that can be implemented. The specification includes a set of function signatures containing type annotations for parameters and return value.

swapped with,

> Traits specify functionality blueprints that can be implemented. The blueprint specification includes a set of function signatures containing type annotations for parameters and return value. This helps standardise the way to implement some specific functionality.

2023-04-16 16:03 UTC, shramee commented on src/ch04-04-traits-in-cairo.md
> +Traits specify functionality blueprints that can be implemented. The specification includes a set of function signatures containing type annotations for parameters and return value.
Just made it more verbose, let me know if this makes more sense.

2023-04-16 16:45 UTC, enitrat approved these changes
LGTM :)

2023-04-16 16:45 UTC, merged