feat: add paths explainations
cairo-book/cairo-book.github.io pull request #55
Opened 2023-04-15 10:55 UTC by fricoben

close #46

2023-04-15 14:58 UTC, enitrat requested changes
Thanks for the PR, however I would change some stuff
- Remove mentions to Rust's `crate::`, instead mention that absolute paths use the crate's name as the root module
- Remove anything that has to do with `super::lib`, this is not intuitive. Examples with super should refer to an explicit parent module directly

2023-04-15 14:58 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +- An _absolute path_ is a full path starting from a crate root, in Rust you use the `crate` keyword to start an absolute path, in Cairo absolute paths are not implemented yet.
I would remove the comparison with Rust here - absolute paths start with the crate name

2023-04-15 14:58 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +    crate::front_of_house::hosting::add_to_waitlist(); // ❌ Doesn't compile in Cairo
I would remove this as well

2023-04-15 14:58 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +    crate::front_of_house::hosting::add_to_waitlist(); // ❌ Doesn't compile in Cairo
absolute path should be something like `restaurant::front_of_house::...` since our crate is named "restaurant", that's what should be shown here

2023-04-15 14:58 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +crate as `eat_at_restaurant`. In rust you can use the `crate` keyword to
same, remove mention to rust, add a mention that you must use the crate name

2023-04-15 14:58 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +use front_of_house::hosting::add_to_waitlist; // used for Relative Method 2
I would say that the `use` keyword to bring items into scope should not be explained here but in #47

2023-04-15 14:58 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +        super::lib::front_of_house::hosting::add_to_waitlist(); // ❌ Doesn't compile
remove this one as well

2023-04-15 14:58 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +```bash
```
```console
```

2023-04-15 15:14 UTC, fricoben commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +- An _absolute path_ is a full path starting from a crate root, in Rust you use the `crate` keyword to start an absolute path, in Cairo absolute paths are not implemented yet.
On my end doing something like this in lib.cairo

```rust 
mod customer_experience {
    mod front_of_house {
        mod hosting {
            fn add_to_waitlist() {}

            fn seat_at_table() {}
        }

        mod serving {
            fn take_order() {}

            fn serve_order() {}

            fn take_payment() {}
        }
    }

    fn eat_at_restaurant() {
        front_of_house::hosting::add_to_waitlist();
        super::lib::front_of_house::hosting::add_to_waitlist();
        lib::customer_experience::front_of_house::hosting::add_to_waitlist();
    }
}
```

the `lib::customer_experience::front_of_house::hosting::add_to_waitlist();` does not compile so we can't say there is an absolute path here. That's why I said there is no absolute path I thought would come in the future.

2023-04-15 15:16 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +- An _absolute path_ is a full path starting from a crate root, in Rust you use the `crate` keyword to start an absolute path, in Cairo absolute paths are not implemented yet.
yeah but the crate name here is not `lib`, it's `restaurant`. It's the one defined in `cairo_project.toml`

2023-04-15 15:19 UTC, fricoben commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +use front_of_house::hosting::add_to_waitlist; // used for Relative Method 2
https://github.com/cairo-book/cairo-book.github.io/pull/55/files/14f85aab09b2a502d5692c37c5062ab978869d91#r1167565620

2023-04-15 15:20 UTC, fricoben commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +    crate::front_of_house::hosting::add_to_waitlist(); // ❌ Doesn't compile in Cairo
[This does not compile for me as I said here](https://github.com/cairo-book/cairo-book.github.io/pull/55/files/14f85aab09b2a502d5692c37c5062ab978869d91#r1167565620)

2023-04-15 15:28 UTC, fricoben commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +- An _absolute path_ is a full path starting from a crate root, in Rust you use the `crate` keyword to start an absolute path, in Cairo absolute paths are not implemented yet.
Understood here I didn't set the restaurant module well

2023-04-15 16:05 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +crate as `eat_at_restaurant`. In Cairo it's not possible you need to specify the crate module identifier,
Something along the lines of:
"In Cairo, absolute paths start from the crate root, which you need to refer to by using the crate name."

2023-04-15 16:05 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +We then included two methods to import `add_to_waitlist` with a relative path.
two "ways" instead of methods maybe?

2023-04-15 16:05 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +We then included two methods to import `add_to_waitlist` with a relative path.
We then included two ways of using `add_to_waitlist` with a relative path.

2023-04-15 16:05 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +mod customer_experience {
I think we should change this example and just use something better to demonstrate how super is useful.

```rust
fn deliver_order() {}

mod back_of_house {
    fn fix_incorrect_order() {
        cook_order();
        super::deliver_order();
    }

    fn cook_order() {}
}
```

here you can see directly that you access a parent's module easily using `super` , which wasn't the case previously

2023-04-15 16:05 UTC, enitrat commented on src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +    use super::front_of_house;
we don't want to use `use` yet in this part

2023-04-16 19:36 UTC, enitrat approved these changes
LGTM

2023-04-16 19:36 UTC, merged