feat: add use keyword usage
cairo-book/cairo-book.github.io pull request #65
Opened 2023-04-17 17:57 UTC by Th0rgal

This closes #47 

I wasn't able to complete the `Using external packages (with Scarb)` section. It might be a problem on my side but I couldn't  use the cairo lib with the quaireaux example. I think it might not be ready so in the meantime I added a note.

What do you think?

2023-04-18 13:22 UTC, enitrat requested changes
The examples don't compile, and there's an overall lack of explanation. It feels like a poor version of the rustbook, because the concepts that translate between the two languages are poorly explained here.

You should directly adapt the Rust Book's page to Cairo, it's of good quality, and we don't need to be creative here.

2023-04-18 13:22 UTC, enitrat commented on src/ch06-04-bringing-paths-into-scope-with-the-use-keyword.md
> +Writing out paths to call functions can be repetitive and inconvenient. To create a shortcut to a path, we can use the `use` keyword, which allows us to use the shorter name within the scope.
To avoid repeting the word "use", let's rephrase it this way:

> We can create a shortcut to a path with the use keyword

2023-04-18 13:22 UTC, enitrat commented on src/ch06-04-bringing-paths-into-scope-with-the-use-keyword.md
> +    pub mod hosting {
`pub` doesn't exist, please make sure the examples work!

2023-04-18 13:22 UTC, enitrat commented on src/ch06-04-bringing-paths-into-scope-with-the-use-keyword.md
> +use crate::front_of_house::hosting;
`use crate`? You need to make sure your examples 😄

2023-04-18 13:22 UTC, enitrat commented on src/ch06-04-bringing-paths-into-scope-with-the-use-keyword.md
> +## Using External Packages in Cairo with Scarb
Ok for now

2023-04-18 13:38 UTC, enitrat commented
Also don't forget to number the listings

2023-04-19 12:44 UTC, Th0rgal commented
> Also don't forget to number the listings And we can now rename imports with `as`

Alright, is it with alpha 7?

2023-04-19 13:28 UTC, enitrat commented
> > Also don't forget to number the listings And we can now rename imports with `as`
> 
> Alright, is it with alpha 7?

yes

2023-04-19 16:26 UTC, enitrat approved these changes

2023-04-19 16:27 UTC, merged