Add Common Collections page + move array to it and add span
cairo-book/cairo-book.github.io pull request #72
Opened 2023-04-18 17:02 UTC by Matth26

Fix issue #62 

- Add **Common Collections** page (ch02-06)
- Move array from **Data Types** to **Common Collections**
- Add span to **Common Collections**

2023-04-18 22:13 UTC, enitrat requested changes
Thanks for the PR! I would like to see some refactoring done on the Array section, with more granularity and explanation. Here are some sections that I would like to see emerging:

### Creating a new Array

### Updating an Array (either `pop_front()` or `append()`)

### Reading Elements from an Array (`get()`, `at()`, `[]`)

### Storing multiple types with Enums


### Spans

#### Turning an Array into a span

2023-04-18 22:13 UTC, enitrat commented on src/ch02-06-common-collections.md
> +Cairo1 provides a set of common collection types that can be used to store and manipulate data. These collections are designed to be efficient, flexible, and easy to use. This section introduces the
> Array and Span.

Array and Felt252Dict. Spans are not "real" collection types

2023-04-18 22:13 UTC, enitrat commented on src/ch02-06-common-collections.md
> +Span is a struct that represents a read-only view or snapshot of an Array. It is designed to provide safe and controlled access to the elements of an array without modifying the original data. Span i
> without modifying the original data

It's probably better to change this to

> without modifying the original array

As the first formulation only includes the existing data, but doesn't explain that we can't modify the array itself

2023-04-19 12:17 UTC, Matth26 commented on src/ch02-06-common-collections.md
> +Without the use of Span, attempting to print the array directly would result in a compile-time error, as the ownership of the array data would be moved to the print() function, and the arr variable w
I tried that yesterday, but got `Method clone not found on type Array` so I thought it was the method to print an array. But got it, I remove this use case!

2023-04-19 12:18 UTC, Matth26 commented on src/ch02-06-common-collections.md
> +#### Methods
Sure it makes sense

2023-04-19 12:23 UTC, Matth26 commented on src/ch02-06-common-collections.md
> +Another good use case is printing an array. In this example, the Span is used for printing the array without modifying the original data. The snapshot field of the Span is then cloned before printing
I noticed this print syntax in a starklings exercise, so I assumed it was the recommended method for printing.

2023-04-19 12:49 UTC, Matth26 commented on src/ch02-06-common-collections.md
> +Without the use of Span, attempting to print the array directly would result in a compile-time error, as the ownership of the array data would be moved to the print() function, and the arr variable w
I'm using the `move_semantics3.cairo` exercice in starklings to test that, and the `array::ArrayTCloneImpl` is imported. I'm probably missing something but don't know what haha

2023-04-19 13:28 UTC, enitrat commented on src/ch02-06-common-collections.md
> +Another good use case is printing an array. In this example, the Span is used for printing the array without modifying the original data. The snapshot field of the Span is then cloned before printing
no it was just a workaround because there was a bug in the v6 compiler

2023-04-19 14:08 UTC, Matth26 commented on src/ch02-06-common-collections.md
> +Another good use case is printing an array. In this example, the Span is used for printing the array without modifying the original data. The snapshot field of the Span is then cloned before printing
Ohh okay thanks!

2023-04-20 07:44 UTC, enitrat approved these changes
LGTM! tyvm :100:

2023-04-20 07:44 UTC, merged