feat:loops
cairo-book/cairo-book.github.io pull request #73
Opened 2023-04-19 12:31 UTC by enitrat

2023-04-19 14:42 UTC, fricoben requested changes
Some comments and questions. 

Learnt things, thx 🔥

2023-04-19 14:42 UTC, fricoben commented on src/ch02-05-control-flow.md
> +the stop condition might never be reached, resulting in an infinite loop.
Will the compiler see here that `i>10` will never happen ?

2023-04-19 14:42 UTC, fricoben commented on src/ch02-05-control-flow.md
> +> Note: Cairo prevents us from running program with infinite loops by including a gas meter. The gas meter is a mechanism that limits the amount of computation that can be done in a program. By setti
Can you briefly define `Panick` here ? from my understanding the program runs out of gas (with the default max gas value).

2023-04-19 14:42 UTC, fricoben commented on src/ch02-05-control-flow.md
> +the stop condition might never be reached, resulting in an infinite loop.
Answered after but might be worth to say that the compiler won't see it directly

2023-04-19 14:42 UTC, fricoben commented on src/ch02-05-control-flow.md
> +```
Maybe be you can give an example with the `--available-gas` flag and a very high condition on `i`

2023-04-19 14:42 UTC, fricoben commented on src/ch02-05-control-flow.md
> +```
You wrote the function two times (the second one might be the on you want to keep).

2023-04-19 14:42 UTC, fricoben commented on src/ch02-05-control-flow.md
> +- Generate the *n*th Fibonacci number.
n-th

2023-04-19 16:09 UTC, enitrat commented on src/ch02-05-control-flow.md
> +> Note: Cairo prevents us from running program with infinite loops by including a gas meter. The gas meter is a mechanism that limits the amount of computation that can be done in a program. By setti
the program runs out of gas, and thus panics with an out of gas error

2023-04-19 16:30 UTC, enitrat commented on src/ch02-05-control-flow.md
> +> Note: Cairo prevents us from running program with infinite loops by including a gas meter. The gas meter is a mechanism that limits the amount of computation that can be done in a program. By setti
you understood it well :)

2023-04-20 08:54 UTC, fricoben approved these changes
LGTM

2023-04-20 08:54 UTC, merged