Starknet contracts: ABIs and cross-contract interactions
cairo-book/cairo-book.github.io pull request #84
Opened 2023-04-24 01:19 UTC by Darlington02

2023-04-24 06:58 UTC, enitrat requested changes
Great PR! Thank you 💯 

A few things to address:
- Can you move the chapter09 before the Appendix in the summary
- We should have an entire section dedicated to smart contracts, something like `ch09-starknet-smart-contracts`. The content you wrote would be a subsection of this section. Can you do this change as well? 
- I think we could merge these pages together to improve the structure of the book
- Add Listing numbering (e.g. Listing 9-1: ERC20 Interface by Openzeppelin)

2023-04-24 06:58 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +```rust
Can you use OZ's implementation here? https://github.com/OpenZeppelin/cairo-contracts/blob/cairo-1/src/openzeppelin/token/erc20.cairo

2023-04-24 06:58 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +ABI stands for Application Binary Interface. ABIs gives a smart contract the ability to communicate and interact with external applications or other smart contracts. ABIs can be likened to APIs in tr
> ABIs can be likened to APIs in traditional web development, which helps data flow between applications and servers.

You should specify that an ABI is just a specification that defines how to encode and decode data when calling smart contract methods

2023-04-24 06:58 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +The Starknet plugin generates a contract interface for your defined contracts, a trait you can find in `<contract_name>::__abi`. But you can also write a contract interface manually to interact with
> The Starknet plugin generates a contract interface for your defined contracts, a trait you can find in `<contract_name>::__abi`.

This sentence is not very clear 🤔

2023-04-24 06:58 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +
I think the most important thing here is missing: Interfaces are implemented with traits in Cairo. It might be worth adding a ref link to the Traits sections, where we specify that traits specify functionality blueprints.

2023-04-24 06:58 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +trait IERC20 {
same, use OZ's (as we want to avoid the use of the `felt252` type generally, we should avoid using it in the book as well, except temporarily for short strings)

2023-04-24 06:58 UTC, enitrat commented on src/ch09-02-contract-dispatcher.md
> +Contracts annotated with the `abi` macro/attribute are programmed to automatically generate and export the relevant dispatcher logic on compilation. The compiler also generates a new trait, two new s
> with the `abi` macro/attribute

just attribute

2023-04-24 06:58 UTC, enitrat commented on src/ch09-02-contract-dispatcher.md
> +    fn get_name(self: T) -> felt252 {
> fn get_name(self: T) -> felt252 {

I think `T` should be `IERC20Dispatcher` here

2023-04-24 07:03 UTC, enitrat commented
Also now that I think about it using the IERC20 example might not be ideal as it's a bit too long and it's probably better if we can restrict the scope so that the reader can experiment with the examples themselves. 

I'll leave it up to you, but this part will probably be reworked later with smarter examples. In the first Contract chapter we will very likely write a simple contract, and it would be cool if the user could write a second contract that makes calls to the contract he wrote previously, and finally test all of this in a third section.

2023-04-25 04:27 UTC, Darlington02 commented
> Great PR! Thank you 💯
> 
> A few things to address:
> 
> * Can you move the chapter09 before the Appendix in the summary
> * We should have an entire section dedicated to smart contracts, something like `ch09-starknet-smart-contracts`. The content you wrote would be a subsection of this section. Can you do this change as well?
> * I think we could merge these pages together to improve the structure of the book
> * Add Listing numbering (e.g. Listing 9-1: ERC20 Interface by Openzeppelin)

So here's the structure I ended up creating..
- Starknet smart contracts  9
       - ABIs and Contract Interactions  9.1
             - ABIs and Interfaces 9.1.1
             - Contract Dispatchers 9.1.2
             - Library Dispatchers and system calls 9.1.3
       
The idea is sections under starknet contracts can go in as subsections, but can also be parent sections to other subsections too...does this make sense to do? Cause I feel like cramming all the subsections under let's say the ABIs and Contract Interactions into one page, might be too overwhelming for the reader

2023-04-25 04:37 UTC, Darlington02 commented on src/ch09-01-abis-and-interfaces.md
> +```rust
Uhmm, I wanted to go that route, but OZ's implementation considers the functions as all internals (which they actually are), so there are no visibilities specified, which I thought might not directly communicate the point to the user (that specifying visibility is important).

Or should I just use them, then let the user know there's no visibility specified because the functions are all internal functions?

2023-04-25 04:47 UTC, Darlington02 commented on src/ch09-01-abis-and-interfaces.md
> +
done

2023-04-25 04:51 UTC, Darlington02 commented on src/ch09-01-abis-and-interfaces.md
> +trait IERC20 {
felts are only returned by the `get_name` and `get_symbol` functions, which returns short strings. the `get_total_supply` was a mistake..was supposed to return a u256 :)

but if you think it's better to go with OZ's implementation, let me know and I'd switch before updating the PR

2023-04-25 07:29 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +```rust
hmm, I see
Let's do both actually: Keep it as you did right now, but just modify the function signatures to match OZ's

2023-04-25 07:29 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +trait IERC20 {
See comment above

2023-04-25 07:31 UTC, Darlington02 commented on src/ch09-01-abis-and-interfaces.md
> +```rust
alright, on it :)

2023-04-25 07:31 UTC, enitrat commented
> Cause I feel like cramming all the subsections under let's say the ABIs and Contract Interactions into one page, might be too overwhelming for the reader

Ok, let's keep it like this for now. We'll see if we end up with too many subsections, or if some can be merged, whether we group them or not.
However I still think at least ContractDispatcher and LibraryDispatcher could be grouped together

2023-04-25 07:37 UTC, Darlington02 commented on src/ch09-02-contract-dispatcher.md
> +```rust
updated

2023-04-25 08:01 UTC, Darlington02 commented on src/ch09-03-library-dispatcher-and-system-calls.md
> +## Calling Contracts using low-level System calls
done

2023-04-25 08:03 UTC, Darlington02 commented
> 

yes, we could have a dedicated section, that's practical oriented, walking the reader through all they've learnt from writing to deploying

2023-04-25 08:19 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +    fn get_name() -> felt252;
these should be named `name()` , `symbol()`, without get prefixes (you will need to modify these names in the text below as well)

2023-04-25 08:20 UTC, enitrat commented on src/ch09-01-abis-and-interfaces.md
> +
Add Listing numbering here

2023-04-25 08:20 UTC, enitrat commented on src/ch09-02-contract-dispatcher.md
> +
And here instead of copy-pasting, just say that we are going to use the IERC20 interface from Listing x.x

2023-04-25 08:22 UTC, enitrat commented on src/ch09-00-01-abis-and-interfaces.md
> +
Can you place the Listing here below the example, as done in previous chapters?

2023-04-25 08:22 UTC, enitrat commented on src/ch09-00-02-contract-dispatcher-library-dispatcher-and-system-calls.md
> +<span class="caption">Listing 9-2: A simple ERC20 Interface</span>
If this is the same as Listing 9-1, we can just refer to Listing 9-1 instead of defining Listing 9-2, which is the same as 9-1

2023-04-25 08:22 UTC, enitrat commented on src/ch09-00-02-contract-dispatcher-library-dispatcher-and-system-calls.md
> +```
Listing 9-2

2023-04-25 08:22 UTC, enitrat commented on src/ch09-00-02-contract-dispatcher-library-dispatcher-and-system-calls.md
> +
Listing 9-4

2023-04-25 10:26 UTC, enitrat approved these changes
💯

2023-04-25 10:26 UTC, merged